name: Build and Deploy to AKS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        function: [sender_function, receiver_function]  # Builds both sender and receiver functions

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: <acr_name>.azurecr.io
        username: ${{ secrets.AZURE_ACR_USERNAME }}
        password: ${{ secrets.AZURE_ACR_PASSWORD }}

    - name: Build and push
      run: |
        cd ${{ matrix.function }}
        docker build -t <acr_name>.azurecr.io/${{ matrix.function }}:latest .
        docker push <acr_name>.azurecr.io/${{ matrix.function }}:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Set up Kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'latest'

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Get AKS credentials
      run: az aks get-credentials --resource-group <resource_group> --name <aks_cluster_name>

    - name: Deploy Sender to AKS
      run: |
        kubectl apply -f k8s/sender-deployment.yaml

    - name: Deploy Receiver to AKS
      run: |
        kubectl apply -f k8s/receiver-deployment.yaml
